### ISSUE TITLE
Do you have a Gitter chat group ? Or any group?

### ISSUE THREAD

**Issue by kotAPI** [punchagan/papers-we-love-hyd#2]
I came across this repo via papers-we-love and I reside in Hyderabad. I'd love to be part of this community and get to know the members if it's still active.

**Comment by talonx** [comment]
Hi Praveen, I am one of the co-organizers. The group is dormant since most of the key people got busy with other things. Given some help I would love to revive this sometime, preserving the original intent of the group, which was to talk about interesting computer science papers. I'm in Hyd too and we can catch up sometime if you're interested.

**Comment by kotAPI** [comment]
Well that's disappointing, I thought this community was on a swing!  I'm more than willing to contribute to this community. We definitely have the people, we just need to get the word out. Let me know if we can chat somewhere on Gitter.

**Comment by talonx** [comment]
Sorry I could not get back, been really hectic. Not sure when I can spare time for this in the near future :(

**Comment by punchagan** [comment]
Now that all events happen online, it may be worth trying to see if there is interest and to revive it. I personally don't think I have the time for it. :)

**Comment by talonx** [comment]
Neither do I, but I would love to hand over things to somebody who has the time.
